### ISSUE TITLE
Report LED states (Caps, Num, Scroll)

### ISSUE THREAD

**Issue by posicat** [jensweimann/esphome_ducky#1]
Just set one of these up tonight, they're great!  Mouse movement is working flawlessly BTW!

It would be great if the Ducky returned the state of the caps/num/scroll lock light as triggers for automation.  Like toggle Scroll lock to disable some scheduled automatons, or hit numlock 3 times to turn something on or off.

**Comment by jensweimann** [comment]
I would use something else in this case, something like https://github.com/hass-agent/HASS.Agent
You can configure custom keyboard shortcuts freely with this. Or some other app and just trigger the Home Assistant Http API. 

But the LED states should be possible nevertheless, https://github.com/NicoHood/HID/blob/master/examples/Keyboard/KeyboardLed/KeyboardLed.ino

I'll look into it when I get the time.

Thank you for the suggestion.

**Comment by jensweimann** [comment]
I've looked it up and unfortunately there is no support for LED states on the MultiReport devices that this project uses. Only SingleReport devices like BootKeyboard has that, but in this case you cannot use Keyboard and Mouse simultaneously. 

So we have to live without this feature.
